# Ubuntu 18 - Base Server

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu18-base-server"
  config.vm.hostname = "ubuntu18-base"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.memory = 4096
    vb.cpus = 2
  end
end
